INSERT INTO MENUITEMS VALUES(DEFAULT,'Snickers',3);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Funyons',3);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Cool Ranch Doritos',4);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Twix',15);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Scooby Gummies',20);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Samoas',4);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Cherry Gum',2);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Bugles',3);
INSERT INTO MENUITEMS VALUES(DEFAULT,'Thin Mints',6);

INSERT INTO INGREDIENTS VALUES(DEFAULT,1,'Peanut',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,1,'Chocolate',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,1,'Caramel',1);

INSERT INTO INGREDIENTS VALUES(DEFAULT,2,'Onions',2);
INSERT INTO INGREDIENTS VALUES(DEFAULT,2,'Fried Fat',1);

INSERT INTO INGREDIENTS VALUES(DEFAULT,3,'Ranch',2);
INSERT INTO INGREDIENTS VALUES(DEFAULT,3,'Chip',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,3,'Corn',1);

INSERT INTO INGREDIENTS VALUES(DEFAULT,4,'Chocolate',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,4,'Caramel',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,4,'Shortbread',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,4,'Space Time Control',12);

INSERT INTO INGREDIENTS VALUES(DEFAULT,5,'Velma',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,5,'Daphne',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,5,'Fred',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,5,'Shaggy',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,5,'Scooby',16);

INSERT INTO INGREDIENTS VALUES(DEFAULT,6,'Coconut',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,6,'Happiness',3);

INSERT INTO INGREDIENTS VALUES(DEFAULT,7,'Cherry',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,7,'Chewy Stuff',1);

INSERT INTO INGREDIENTS VALUES(DEFAULT,8,'Cone',1);
INSERT INTO INGREDIENTS VALUES(DEFAULT,8,'Corn',2);

INSERT INTO INGREDIENTS VALUES(DEFAULT,9,'Poor Taste',3);
INSERT INTO INGREDIENTS VALUES(DEFAULT,9,'Bad Decisions',3);


