
CREATE TABLE MENUITEMS
{

    ITEMID      BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME        VARCHAR(15) NOT NULL,
    PRICE       INTEGER NOT NULL,

    CONSTRAINT PK_MENUITEMS PRIMARY KEY(ITEMID)
};

CREATE TABLE ingredients
{

    ID      BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    itemid       bigint not null,
    NAME        VARCHAR(15) NOT NULL,
    PRICE       INTEGER NOT NULL,

}