
CREATE TABLE MENUITEMS
{

    ITEMID      BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME        VARCHAR(15) NOT NULL,
    PRICE       INTEGER NOT NULL,

    CONSTRAINT PK_MENUITEMS PRIMARY KEY(ITEMID)
};

CREATE TABLE ingredients
{

    ID          BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    ITEMID      BIGINT NOT NULL,
    NAME        VARCHAR(15) NOT NULL,
    PRICE       INTEGER NOT NULL,

    CONSTRAINT PK_INGREDIENTS PRIMARY KEY(ID),
    CONSTRAINT FK_TO_MENUITEMS FOREIGN KEY(ITEMID) REFERENCES MENUITEMS(ITEMID)
};